run:
  # Use recommended exclude options
  issues:
    exclude-files:
      - "*.generated.go"

linters:
  enable:
    - staticcheck
    - gosimple
    - unused

linters-settings:
  govet:
    # Replace check-shadowing with shadow
    enabled-checks:
      - shadow
